### PR TITLE
Adjust gyp for locale string resource generation.

### PR DESCRIPTION
**Pull request by seanlong**
Let's use gyp 'copies' to do recursive directory copy.

### CODE REVIEW

**Comment by seanlong** [comment]
@rakuco, thanks.

**Comment by rakuco** [comment]
Didn't you say `copies` did not do recursive copies before? Why not just change the existing action instead of creating another target?

**Comment by seanlong** [comment]
I misunderstood the "Gyp doesn't have any built-in looping capability" comment in https://code.google.com/p/chromium/codesearch#chromium/src/chrome/tools/build/repack_locales.py. The "copies" does support copy a directory recursively to another directory.

The "copies" source directory has dependency on grit_action.gypi generated locales, so another target is needed. Like other pak resource targets.

**Comment by rakuco** [comment]
> The "copies" source directory has dependency on grit_action.gypi generated locales, so another target is needed. Like other pak resource targets.

But if you specify the two actions one after the order aren't they going to be run in the order you specify, so that the output one produces is available as input to the other?

**Comment by seanlong** [comment]
PR updated.
Seems the missing bit is : ```+          'outputs': [ '<(grit_out_dir)' ]```, otherwise  the "copies" input dependencies will lose: ```ninja: error: 'gen/xwalk/locales', needed by 'locales', missing and no known rule to make it```.

**Comment by rakuco** [comment]
excellent, thanks!

**Pull request merged**
