### PR TITLE
[Android] Fix Javadoc error

### PR DESCRIPTION
**Pull request by lincsoon**
This patch is to fix the error when generating Javadoc for embedding API

### CODE REVIEW

**Comment by lincsoon** [comment]
@rakuco Please help to review

**Comment by rakuco** [comment]
Please be more specific in both your commit and pull request messages:
* What javadoc error are you talking about?
* How are you fixing it?
* When was it introduced?

**Comment by lincsoon** [comment]
done

**Comment by rakuco** [comment]
lgtm, thanks!

**Comment by rakuco** [comment]
merged, please remember to cherry-pick to crosswalk-14 if appropriate.

**Pull request merged**
