### PR TITLE
Enable libnotify-based Web Notification by default for Linux.

### PR DESCRIPTION
**Pull request by PeterWangIntel**
Enable libnotify-based Web Notification by default for Linux.

### CODE REVIEW

**Comment by yongkang** [comment]
Peter, could you make sure the patch won't break linux and tizen build and ask Raphal's help to merge?

**Comment by rakuco** [comment]
I've installed libgdk-pixbuf2.0-dev on linux and libnotify-dev on Tizen, please resubmit and see if it's passing now.

**Comment by rakuco** [comment]
Why was this PR closed?

**Comment by PeterWangIntel** [comment]
I'm so sorry. I don't know. I just executed "git push -f origin enable_libnotify:enable_libnotify", then the PR shows closed.

**Pull request closed without merging**
