### PR TITLE
Change scoped_ptr.Pass() to std::move(scoped_ptr) part4

### PR DESCRIPTION
**Pull request by Bysmyyr**
Scoped ptr is deprecated in M49 and it is easier to
fix them directly here. There will be most
probably another similar commit because it is easier to
find them from build failures.

### CODE REVIEW

**Comment by rakuco** [comment]
Are there any other remaining parts after this one? If so, what's the benefit of landing this in parts versus changing everything in one PR?

**Comment by Bysmyyr** [comment]
Those are all from linux build. There can be some when building with android. Those was just miss from last one. I can wait if that makes things much easier.

**Comment by rakuco** [comment]
I don't really see the value in splitting this change into several pull requests, at least I don't see any logical separation being done. So if you have any additional Android changes, please add them to this PR so we change everything that's left at once.

**Comment by Bysmyyr** [comment]
Now there should be all.

**Comment by rakuco** [comment]
lgtm, let's do this

**Pull request merged**
