### PR TITLE
Fix ASSERTs and low quality assets on high dpi screens

### PR DESCRIPTION
**Pull request by darktears**
Right now we're shipping only assets with 100% scale factor. This
patch address the issue by making sure that we at least support
better assets when the scale factor is not 100%.

This will require a change in app-tools as well.

### CODE REVIEW

**Comment by darktears** [comment]
@lincsoon can you have a look please?

@r0b5t4 I need a fix in app-tools see : https://github.com/darktears/crosswalk-app-tools/commit/21443043f963f35679bb901e001a63cac63b401f but how do we proceed because these files will start to show up after a given version. Anything else I missed?

**Comment by r0b5t4** [comment]
@darktears we can add all .pak files just like we do for dll files already. Would that work? The code is right below where you patched it.

**Comment by darktears** [comment]
@r0b5t4 yep I guess we can do that indeed.

**Comment by darktears** [comment]
PR for app tool is there : https://github.com/crosswalk-project/crosswalk-app-tools/pull/132

**Comment by darktears** [comment]
ping @lincsoon

**Comment by lincsoon** [comment]
LGTM for the Android part

**Pull request merged**
