### PR TITLE
[Android] Make shared mode prompt more clearly

### PR DESCRIPTION
**Pull request by lincsoon**
1. Change the wording on the positive button from “Continue” to
“Get Crosswalk”
2. Change "application store" to "app store"
3. The term “runtime” has no meaning to an end user, it is a highly
technical term. Change it to "Add-on"

BUG=XWALK-4801

### CODE REVIEW

**Comment by lincsoon** [comment]
@baleboy @rakuco @halton Please help to review

**Comment by halton** [comment]
LGTM after check with the bug discussion. I'll merge it after @baleboy 's lgtm.

**Comment by baleboy** [comment]
There was some further discussion about the name "Add-on" and finally "Service" was considered a better option. LGTM if you can replace "Add-on" with "Service".

**Comment by lincsoon** [comment]
Done!

**Pull request merged**
