### PR TITLE
Revert "Wifi Direct Experimental API initial contribution"

### PR DESCRIPTION
**Pull request by rakuco**
This reverts commit ef2dad6c381e35eb5424c8d789a6d2b60704a54b.

Reason: breaks `org.xwalk.runtime.client.embedded.test.PauseResumeTest#testPauseAndResume`.

```
E/AndroidRuntime( 9436): FATAL EXCEPTION: main
E/AndroidRuntime( 9436): java.lang.RuntimeException: Unable to resume activity {org.xwalk.runtime.client.embedded.shell/org.xwalk.runtime.client.embedded.shell.XWalkRuntimeClientEmbeddedShellActivity}: java.lang.NullPointerException
E/AndroidRuntime( 9436):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2974)
E/AndroidRuntime( 9436):        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3003)
E/AndroidRuntime( 9436):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
E/AndroidRuntime( 9436):        at android.os.Handler.dispatchMessage(Handler.java:108)
E/AndroidRuntime( 9436):        at android.os.Looper.loop(Looper.java:152)
E/AndroidRuntime( 9436):        at android.app.ActivityThread.main(ActivityThread.java:5691)
E/AndroidRuntime( 9436):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 9436):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 9436):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 9436):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 9436):        at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime( 9436): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 9436):        at android.app.ActivityManagerProxy.registerReceiver(ActivityManagerNative.java:2150)
E/AndroidRuntime( 9436):        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1517)
E/AndroidRuntime( 9436):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1485)
E/AndroidRuntime( 9436):        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1479)
E/AndroidRuntime( 9436):        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:448)
E/AndroidRuntime( 9436):        at org.xwalk.core.internal.extension.api.wifidirect.WifiDirect.onActivityStateChange(WifiDirect.java:343)
E/AndroidRuntime( 9436):        at org.xwalk.core.internal.extension.XWalkExtensionWithActivityStateListener$XWalkActivityStateListener.onActivityStateChange(XWalkExtensionWithActivityStateListener.java:33)
E/AndroidRuntime( 9436):        at org.chromium.base.ApplicationStatus.onStateChange(ApplicationStatus.java:203)
E/AndroidRuntime( 9436):        at org.chromium.base.ApplicationStatus.access$100(ApplicationStatus.java:24)
E/AndroidRuntime( 9436):        at org.chromium.base.ApplicationStatus$2.onActivityResumed(ApplicationStatus.java:149)
E/AndroidRuntime( 9436):        at android.app.Application.dispatchActivityResumed(Application.java:174)
E/AndroidRuntime( 9436):        at android.app.Activity.onResume(Activity.java:1092)
E/AndroidRuntime( 9436):        at org.xwalk.core.XWalkActivity.onResume(XWalkActivity.java:130)
E/AndroidRuntime( 9436):        at org.xwalk.app.XWalkRuntimeActivityBase.onResume(XWalkRuntimeActivityBase.java:67)
E/AndroidRuntime( 9436):        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1185)
E/AndroidRuntime( 9436):        at android.app.Activity.performResume(Activity.java:5207)
E/AndroidRuntime( 9436):        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2964)
E/AndroidRuntime( 9436):        ... 10 more
W/ActivityManager( 2186): Error in app org.xwalk.runtime.client.embedded.shell running instrumentation ComponentInfo{org.xwalk.runtime.client.embedded.test/android.test.InstrumentationTestRunner}:
W/ActivityManager( 2186):   java.lang.NullPointerException
W/ActivityManager( 2186):   java.lang.NullPointerException: Unable to resume activity {org.xwalk.runtime.client.embedded.shell/org.xwalk.runtime.client.embedded.shell.XWalkRuntimeClientEmbeddedShellActivity}: java.lang.NullPointerException
```

### CODE REVIEW

**Comment by rakuco** [comment]
This reverts #3327.
Ping @halton and @astojilj (merger and author). See https://build.crosswalk-project.org/builders/Crosswalk%20Tests%20%28Android%20x86%29/builds/1673 (reverting the commit locally and building from scratch fixes that test, so my commit is not guilty).

**Comment by kenchris** [comment]
lgtm

**Comment by astojilj** [comment]
@rakuco thanks. I'll work on fixing it today.

**Comment by r0b5t4** [comment]
@astojilj one comment about the patch, although this is not really the right place.

I see you added permissions to the default template. This is a questionable approach that has brought us bad press about being insecure in the past. Not every permission for every feature we possibly support, needs to be in the default AndroidManifest.xml. People should enable permissions for the features they are using.

Also CC @baleboy.

**Comment by astojilj** [comment]
Thanks. What is the proper place to discuss permissions handling - let's
move it there.
Kind Regards,
Aleksandar

**Comment by astojilj** [comment]
@r0b5t4 I'll submit revert of revert with the fix, for review later, will
cc you. Let's do it there.
Kind Regards,
Aleksandar

**Pull request merged**
