### PR TITLE
[Android] Initialize NetworkChangeNotifier after loadXWalkLibrary

### PR DESCRIPTION
**Pull request by axinging**
Follow the design of chrome for android, initialize NetworkChangeNotifier after loadXWalkLibrary.

BUG=XWALK-4514

### CODE REVIEW

**Comment by axinging** [comment]
@lincsoon  @halton  @fujunwei

**Comment by halton** [comment]
@axinging code LGTM. 

Could you explain in git log why you move NetworkChangeNotifier code from XWalkViewInternal to XWalkViewDelegate will resolve the bug?

**Comment by axinging** [comment]
This is the original design which works fine. You may refer to https://github.com/crosswalk-project/crosswalk/commit/021bfe092f22fd7e266947795f0a8a9541db2e73, lin 1338,146.

**Comment by halton** [comment]
> This is the original design which works fine. You may refer to 021bfe0, line 138,146.

@axinging I'm confused. What do you mean works fine? But you still upload this PR?

**Comment by axinging** [comment]
Here the original design means before https://github.com/crosswalk-project/crosswalk/commit/021bfe092f22fd7e266947795f0a8a9541db2e73 merged:
In the original design,  the sequence is:
loadXWalkLibrary
NetworkChangeNotifier.init


But PR https://github.com/crosswalk-project/crosswalk/commit/021bfe092f22fd7e266947795f0a8a9541db2e73 change this to:
NetworkChangeNotifier.init
loadXWalkLibrary

So  what I do here is revert the sequence. I verified this on QA provided case, it works.

**Comment by halton** [comment]
Thanks for explanation, I'm going to merge.

**Pull request merged**
