### PR TITLE
To disable Accessibility support

### PR DESCRIPTION
**Pull request by PeterWangIntel**
This feature is about supporting disabled people, such as reading screen.
Since it's pretty independent in code, so it's harmless for the stability of code to disable it.

Reduced size = 72K

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton

**Comment by r0b5t4** [comment]
"So, It's harmless to disable it."
It is not that simple. For people who are disabled, it is quite important indeed. Additionally, in some countries this functionality is required to be eligible for contracts from official agencies (magistrate/government etc). Needs to be considered carefully, on non-technical reasons.

**Comment by baleboy** [comment]
Agree that for those who need it, this is very important. Also is it really worth removing it for a 72K gain?

**Comment by heke123** [comment]
Actually what we did is adding a flag to control it, instead of just remove it.  So for users need this function, we just open the flag, then everything is OK.  and for those who don't want this and care about the binary size, we can delete this function.

**Comment by heke123** [comment]
I agree that those non-tech reasons are really very important, so we need to consider when to use the "disable flag" carefully.

**Comment by PeterWangIntel** [comment]
@r0b5t4 @baleboy ,
Seems, there is misunderstanding. For CrosswalkLite, we're providing series of patch to 'disable' some features, but all of them are optional. The App developer can choose 'enable' or 'disable' the features for the special scenario of their App.

**Comment by r0b5t4** [comment]
@PeterWangIntel thanks for the clarification. I do agree that small size is important, and for some applications like some games the feature might not be useful.

**Comment by baleboy** [comment]
Same here, sorry for misunderstanding

**Comment by PeterWangIntel** [comment]
@r0b5t4 @baleboy ,
No problem. My code comments should be improved.

**Comment by heke123** [comment]
LGTM

**Comment by PeterWangIntel** [comment]
@halton 
Please help to merge, thx.

**Comment by PeterWangIntel** [comment]
@halton 
Please help to merge. Thx.

**Pull request merged**
