### PR TITLE
[Lite] [Android] Conditional disable builtin extensions

### PR DESCRIPTION
**Pull request by heke123**
Disable/Enable is controlled by the GYP flag disable_builtin_extensions.

This flag is 1 for the Lite branch.

BUG=XWALK-3436

### CODE REVIEW

**Comment by zliang7** [comment]
"builtin", not "buildin"

**Comment by halton** [comment]
`[Lite][Android]` -> `[Lite] [Android]`. And please change buildin to builtin in all places as @zliang7 suggested.

**Comment by heke123** [comment]
@halton , modification done, please help to give a review. thanks.

**Comment by halton** [comment]
LGTM, merging. Please monitor the [buildbot] (https://build.crosswalk-project.org/waterfall) status because we do not have trybot to check.

**Pull request merged**
