### PR TITLE
[Android] Fixed building error

### PR DESCRIPTION
**Pull request by lincsoon**
Build entire java libraries before generate xwalk_shared_library

BUG=XWALK-4746

### CODE REVIEW

**Comment by halton** [comment]
LGTM, merging.

**Comment by rakuco** [comment]
Isn't this needed in master too?

**Comment by halton** [comment]
Yes,  @lincsoon suppose to submit PR to master.

**Comment by rakuco** [comment]
:(
Then I really don't get why it was not submitted to master and cherry-picked later like we always do.

**Comment by rakuco** [comment]
I'm still waiting for another pull request... And now it needs to target crosswalk-15 in addition to master.

**Comment by lincsoon** [comment]
Sorry, I took one week leave from last week. Logically, this patch also applies to the master branch. But I haven't found building error in the master branch even without this patch. So I was checking why the building error only occurs in the crosswalk-14 branch. But it seems @rakuco has helped to cherry-pick this patch to the master and crosswalk-15 branch.

**Pull request merged**
