### PR TITLE
Disable webcl

### PR DESCRIPTION
**Pull request by PeterWangIntel**
To disable WebCL    
    Leverage existing flag "enable_webcl" to disable functions and exclude
    related code in Blink.    
    Reduced size = 44K

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton 
Please have a look. 

The pair patch is 
https://github.com/crosswalk-project/blink-crosswalk/pull/84

**Comment by PeterWangIntel** [comment]
@heke123 @halton 
It will pass compile with crosswalk-project/blink-crosswalk#84 applied in Blink repo.

**Comment by PeterWangIntel** [comment]
@heke123 
It's not necessary. thx.

**Comment by PeterWangIntel** [comment]
@heke123

**Comment by heke123** [comment]
LGTM

**Comment by halton** [comment]
@PeterWangIntel please force update to re-trigger the trybot

**Comment by PeterWangIntel** [comment]
@halton , please help to merge

**Pull request merged**
