### PR TITLE
[Android] Optimizing layout hierarchy of XWalkView

### PR DESCRIPTION
**Pull request by axinging**
Decouple XWalkContent from FrameLayout, this can reduce the XWalkView's 4 level view hierarchy to
to 3.
BUG=XWALK-4760

### CODE REVIEW

**Comment by axinging** [comment]
@lincsoon  @fujunwei  @halton

**Comment by axinging** [comment]
@halton  @lincsoon

**Comment by halton** [comment]
LGTM @axinging please rebase

**Comment by lincsoon** [comment]
LGTM

**Comment by axinging** [comment]
@halton @lincsoon , interesting! Rebase works!

**Comment by halton** [comment]
Thanks, will merge after trybot green.

**Pull request merged**
