### PR TITLE
Encode the data by base64 to load that as a data: URL

### PR DESCRIPTION
**Pull request by fujunwei**
Document the API doc for XWalkCookieManager.

BUG=XWALK-3571

### CODE REVIEW

**Comment by fujunwei** [comment]
@lincsoon @axinging @halton PTAL, thanks.

**Comment by lincsoon** [comment]
Please separate this to two commits, and cherry-pick the change about java doc to crosswalk-14 and 15.

**Comment by fujunwei** [comment]
@lincsoon thanks, done.

**Comment by lincsoon** [comment]
LGTM

**Comment by halton** [comment]
Will merge after trybot green.

**Comment by rakuco** [comment]
This has broken several tests, so I'll have to revert this PR:
https://build.crosswalk-project.org/builders/Crosswalk%20Tests%20%28Android%20x86%29

**Pull request merged**
