### PR TITLE
 Roll to chromium 43.0.2357.37

### PR DESCRIPTION
**Pull request by Bysmyyr**
Change one function name based on changes in chromium.

### CODE REVIEW

**Comment by rakuco** [comment]
Thanks. I've finally pushed the new forks so the next trybot attempt should pass. So please:

1. Squash your commits into one, otherwise the build will be broken between the two commits.
1. Update the pull request message as it still mentions the test that was being disabled.
1. Resubmit to get the bots to test the patch.

**Comment by rakuco** [comment]
The oz-wl build is broken

**Comment by Bysmyyr** [comment]
I see, I have problems with my computer, so hope I managed to fix that. I am out tomorrow.

On Wed Apr 29 09:56:11 2015 GMT+0300, Raphael Kubo da Costa wrote:
> The oz-wl build is broken
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/crosswalk-project/crosswalk/pull/3000#issuecomment-9732744

--

**Comment by rakuco** [comment]
Fix pending in 01org/ozone-wayland#378.

**Comment by rakuco** [comment]
I've now moved our forks to 43.0.2357.45, which was released last night. The oz-wl PR I mentioned above is still pending, but let's close this one and send a new PR for .45 next week.

**Pull request closed without merging**
