### PR TITLE
M44 Rebase: Update the Remote Debugging and DevTools as per upstream …

### PR DESCRIPTION
**Pull request by mrunalk**
…changes

The DevToolsHttpHandler has been componentized upstream

https://codereview.chromium.org/1086623002
https://codereview.chromium.org/1089413002
https://codereview.chromium.org/1056343004
https://codereview.chromium.org/1114503002

### CODE REVIEW

**Comment by halton** [comment]
Add @PeterWangIntel in loop since he ever did that area.

**Comment by mrunalk** [comment]
@PeterWangIntel can you please take a look?

**Comment by PeterWangIntel** [comment]
@halton @mrunalk , sorry, I just noticed, will have a look and give comments ASAP.

**Comment by PeterWangIntel** [comment]
@mrunalk @halton ,
I'm still fighting to download the code of Chromium... 

I'm not familiar the standard working process of "Rebase" mentioned here, my personal suggestion is that we can disable devtools temporarily, like pull request #3049 shows.

Once the "M44 Rebase" is finished, I believe I can download the stable code to make 'devtools' working within 1~2 days.

**Comment by rakuco** [comment]
The process is essentially:

1. Make sure your chromium/v8/blink/ozone-wayland checkouts are detached (`git checkout --detach`)
1. Switch to Crosswalk's "next" branch
1. `gclient sync`

The build might break if there is code that still needs to be merged, as is probably the case at the moment.

Given the first days after a rebase are usually a bit tumultuous anyway, I think we could go ahead without disabling devtools: it would be good if you could just take a look at the CLs linked in the pull request message and Mrunal's patch and see if there is anything obvious that was overlooked. If not, we can go ahead and fix any regressions afterwards (or during the rebase cycle once the code is buildable).

**Comment by mrunalk** [comment]
Yeah, I just wanted you to review the code. We can fix the regressions later. Considering the deadline is approaching faster I will go ahead and merge this patch for now.

**Pull request merged**
