### PR TITLE
[Android] Auth dialog password shown in plain text

### PR DESCRIPTION
**Pull request by marcuspridham**
BUG=XWALK-5659

### CODE REVIEW

**Comment by rakuco** [comment]
it looks ok to me, but I was expecting somebody with an Android hat to take a look at this.
ping @wuhengzhi @lincsoon @XiaosongWei

**Comment by wuhengzhi** [comment]
LGTM, thanks.

**Comment by rakuco** [comment]
@marcuspridham: thanks a lot for your patch. would you mind sending a new pull request backporting it to the crosswalk-16 branch? you just need to use `git cherry-pick -x` (the `-x` is important) and send a new PR.

**Comment by marcuspridham** [comment]
Thanks.  The pull request for crosswalk-16 is here: https://github.com/crosswalk-project/crosswalk/pull/3385

**Pull request merged**
