### PR TITLE
Fix TC-1666: Add the possibility to launch app in debug on Tizen

### PR DESCRIPTION
**Pull request by baillaw**
BUG-Tizen=TC-1666
BUG=XWALK-2729

Signed-off-by: Baptiste DURAND <baptiste.durand@open.eurogiciel.org>

### CODE REVIEW

**Comment by baillaw** [comment]
@tiwanek : as the changes that you pointed is reverted now due to regression,
https://review.tizen.org/gerrit/gitweb?p=platform/framework/web/crosswalk.git;a=commit;h=c833a47ff3935fca72614f6cb1f6c6555bf59151

could you accept this change?

**Comment by tiwanek** [comment]
Is this really needed? Related tizen.org bug is closed as I see.

**Comment by baillaw** [comment]
Because is already merged in Tizen.... :)

2015-01-07 9:35 GMT+01:00 Tomasz Iwanek <notifications@github.com>:

> Is this really needed? Related tizen.org bug is closed as I see.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crosswalk-project/crosswalk/pull/2503#issuecomment-68992449>
> .
>



-- 
Baptiste DURAND

**Comment by tiwanek** [comment]
Oh, ok... I have no objections.

I hope it is not final solution (I assume aul still sends information about debug in bundle).

**Comment by baillaw** [comment]
I know that the solution is not clean :S
BTW we are changing the runtime process model ... so the changes will not
be relevant when we will deactivate shared process mode.


2015-01-07 9:58 GMT+01:00 Tomasz Iwanek <notifications@github.com>:

> Oh, ok... I have no objections.
>
> I hope it is not final solution (I assume aul still sends information
> about debug in bundle).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crosswalk-project/crosswalk/pull/2503#issuecomment-68994456>
> .
>



-- 
Baptiste DURAND

**Comment by rakuco** [comment]
Closing, Tizen is out of scope now.

**Pull request closed without merging**
