### PR TITLE
Fix: Unexpected os.arch: armv8l

### PR DESCRIPTION
**Pull request by yuliskov**
Error happened when user clicks Get Crosswalk button on Crosswalk dialog.

### CODE REVIEW

**Comment by rakuco** [comment]
@sunlin-link

**Comment by rakuco** [comment]
@sunlin-link: re-ping

**Comment by poohbear80** [comment]
any chance on merging this? we had to fix this locally

**Comment by rakuco** [comment]
I guess it doesn't hurt after all.

**Pull request merged**
