### PR TITLE
[Android] Fix the NewApi warnings.

### PR DESCRIPTION
**Pull request by wuhengzhi**
Some new APIs were used without runtime checks, app will be crashed when
it runs on lower API level devices.
Add the checks for new APIs.

BUG=XWALK-6296, XWALK-6495

### CODE REVIEW

**Comment by wuhengzhi** [comment]
@fujunwei @lincsoon @XiaosongWei @xzhan96 @axinging @rakuco  PTAL, thanks.

**Comment by rakuco** [comment]
Since these crashes are also possibly present on older releases, this patch needs to be made as small as possible: no unnecessary style fixes, for example. Please there are only fixes for potential crashes (even then I'm still afraid that this can break Crosswalk 18).

**Comment by vbresults** [comment]
@rakuco I don't see anything that can be subtracted.

**Comment by wuhengzhi** [comment]
@rakuco
Code style fixes has been removed, all of others are related to `NewApi`.
It won't break Crosswalk-18.
Thanks.

**Comment by halton** [comment]
@kenny-y could you please review this PR? This one is Presentation API related.

**Comment by baleboy** [comment]
@kenny-y would appreciate if you could prioritize this, it's about fixing a release blocker for Crosswalk 18

**Comment by kenny-yuan** [comment]
I don't have anything to comment as long as it works :) Part of this change (1/6) is actually fixing my bad in my previous PR. Thanks for everyone working on this.

And can't help thinking: is there anyone who's more familiar in this area to do this review? Thanks.

**Comment by halton** [comment]
@kenny-y , 

Normally as a reviewer, it is fact that we could not understand totally line by line. Most of times, give a general review is enough. Otherwise we're ***too fear mistakes to step***. Besides, we have QA as gatekeeper.

Back to this PR, I can see this PR is mostly Presentation API (Android) related, I suppose you're best person to review so far.  I'll be appropriated if you can give your explicit LGTM. 

> I don't have anything to comment as long as it works :) Part of this change (1/6) is actually fixing my bad in my previous PR. Thanks for everyone working on this.

> And can't help thinking: is there anyone who's more familiar in this area to do this review? Thanks.

**Comment by kenny-yuan** [comment]
@halton Actually it's not about responsibility-taking in my point of view, I got the sense that a culprit is not eligible to make the decision of his own bad (kinda like "conflict of interest") :)

I'll look into it and comment later.

**Comment by kenny-yuan** [comment]
Well my answer is positive. LGTM. I believe it can keep the expected behavior when running on higher version Android, and at the same time avoid runtime issue when running on lower version Android.

**Comment by halton** [comment]
@kenny-y thanks for your review, I'm going to merge this PR.

**Comment by vbresults** [comment]
The only way to access this is to use crosswalk 19 yes?

**Comment by wuhengzhi** [comment]
For now, answer is Yes. I will back port to Crosswalk 18.

**Comment by vbresults** [comment]
@wuhengzhi Do you have any idea of the timeline?

**Comment by wuhengzhi** [comment]
@vbresults Please look at https://github.com/crosswalk-project/crosswalk/pull/3610, it will be merged to Crosswalk 18.

**Comment by vbresults** [comment]
Thank you :+1:

**Pull request merged**
