### PR TITLE
[Android] Fix the display for the website's title after navigation.

### PR DESCRIPTION
**Pull request by wuhengzhi**
This patch is to display the website's title when open multiple URLs and
press the back or forward button.
The event of update title will be fired in render frame host and title will be
compared to the one in navigation entry, if they are same, the update
title event will not be sent to Java layer.

BUG=XWALK-2333

### CODE REVIEW

**Comment by rakuco** [comment]
Don't we need tests?

**Comment by wuhengzhi** [comment]
@rakuco The fixing is for displaying the title on tab in XWalkCoreShell, I have verified the title manually.
Refine the test case for navigation and add test case for onLoadFinished to ensure the title is identical.

**Comment by wuhengzhi** [comment]
@lincsoon @axinging @fujunwei PTAL. Thanks

**Comment by axinging** [comment]
LGTM. Thanks for quick patch.

**Comment by lincsoon** [comment]
LGTM

**Comment by lincsoon** [comment]
@rakuco

**Comment by rakuco** [comment]
Please backport if needed.

**Pull request merged**
