### PR TITLE
Commit the lzma SDK instead of fetching it.

### PR DESCRIPTION
**Pull request by darktears**
Remove the hooks to fetch the SDK, there is no need to download it,
it's small enough to import the files directly in our repository.

Added README.xwalk to describe the licensing.

### CODE REVIEW

**Comment by rakuco** [comment]
We also need a `README.xwalk` similar to the `README.chromium` files that Chromium adds to its third-party libraries, with information such as where the code came from, the license, what it does etc. See the `README.chromium`s in `src/third_party`, for example.

**Comment by darktears** [comment]
If we go that road, in order for the infra, as well as dev checkouts to not fail we would need to land https://github.com/crosswalk-project/crosswalk/pull/3015 first.

**Comment by rakuco** [comment]
ping @halton @d0ngjun

**Comment by d0ngjun** [comment]
LGTM

**Comment by rakuco** [comment]
given the bot errors are unrelated, let's merge

**Pull request merged**
