### PR TITLE
Remove fake external extension api

### PR DESCRIPTION
**Pull request by heke123**
Decide to add lite support in cordova plugin 1.6.x, so we don't need
this fake external extension api now.
Note that after cordova plugin upgrade into 1.7.0, we need to add
this api back.

### CODE REVIEW

**Comment by heke123** [comment]
@halton @PeterWangIntel  Thanks.

**Comment by halton** [comment]
@heke123 I think this change is reverting PR https://github.com/crosswalk-project/crosswalk/pull/3598? could you use reverting to make the two PRs them connected.

**Comment by halton** [comment]
LGTM, will merge after trybot green.

**Comment by heke123** [comment]
@halton @PeterWangIntel   changed into "git revert",  thanks:)

**Pull request merged**
