### PR TITLE
M52: Fix the failed test cases.

### PR DESCRIPTION
**Pull request by wuhengzhi**
1. Adapt to https://codereview.chromium.org/1785953002
2. Add annotations for test cases.

BUG=XWALK-7104

### CODE REVIEW

**Comment by wuhengzhi** [comment]
@mrunalk PTAL, thanks.

For some new test cases in core shell, ```--test_data="xwalkview:xwalk/test/android/data/device_files/"``` should be added to command line.

**Comment by mrunalk** [comment]
LGTM. @wuhengzhi Good to know. So we will need to use  `--test_data="xwalkview:xwalk/test/android/data/device_files/"` for XWalkCoreTest  apart from XWalkCoreInternalTest?

**Comment by wuhengzhi** [comment]
@mrunalk Yes.

**Comment by mrunalk** [comment]
@wuhengzhi, does that require a change on the infrastructure side to add this parameter?

**Comment by wuhengzhi** [comment]
Yes. Like this ```./build/android/test_runner.py instrumentation --release --test-apk=XWalkCoreTest --test_data="xwalkview:xwalk/test/android/data/device_files/"```

**Comment by mrunalk** [comment]
@rakuco, ^^^^^. As suggested above we need to update the test parameters on infrastructure side.

**Comment by rakuco** [comment]
Done; the Buildbot code has been adjusted.

**Comment by mrunalk** [comment]
thanks @rakuco

**Pull request merged**
