### PR TITLE
[Android] Remove tar.py and the pack_* targets from gyp

### PR DESCRIPTION
**Pull request by rakuco**
`pack_xwalk_core_library` was created years ago when we had our own
Cordova 3 fork and suggested people extracted the xwalk_core_library
tarball into its checkout.

This has not been the case for a long time, and our release build system
does not use any of those `pack_*` targets to create its zip files.
Anyone wishing to create a tarball out of the directories in `out/` can
do so manually.

### CODE REVIEW

**Comment by rakuco** [comment]
@lincsoon @heke123 @wuhengzhi @darktears

**Comment by wuhengzhi** [comment]
Should ```pack_xwalk_core_library_src``` also be removed?

**Comment by rakuco** [comment]
As far as I can see, `pack_xwalk_core_library_src` is an action that's being removed as part of `pack_xwalk_core_library`.

**Comment by wuhengzhi** [comment]
Oh, LGTM, thanks.

**Comment by heke123** [comment]
LGTM

**Pull request merged**
