### PR TITLE
DEPS.xwalk: Roll chromium-crosswalk (13ee6cc -> bfb8dc3).

### PR DESCRIPTION
**Pull request by tmpsantos**
SSIA

### CODE REVIEW

**Comment by tmpsantos** [comment]
@pozdnyakov @rakuco

**Comment by pozdnyakov** [comment]
lgtm

**Comment by rakuco** [comment]
you're supposed to indicate which commits are being pulled, please take a look at the commit history for `DEPS.xwalk` to see what it looks like.

**Comment by tmpsantos** [comment]
> you're supposed to indicate which commits are being pulled, please take a look at the commit history for DEPS.xwalk to see what it looks like.

Done!

**Pull request merged**
