### PR TITLE
To disable WebVideo

### PR DESCRIPTION
**Pull request by PeterWangIntel**
With flag "-Ddisable_web_video=1" the size is reduced by 180K.

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@d0ngjun

**Comment by PeterWangIntel** [comment]
It's similar to the patch of to disable audio. a small patch. please have a look.

**Comment by d0ngjun** [comment]
LGTM

**Comment by halton** [comment]
@PeterWangIntel  please rebase

@d0ngjun same question, merge now or wait for crosswalk-15 rebasing?

**Comment by halton** [comment]
@PeterWangIntel please rebase so that I can merge.

**Comment by PeterWangIntel** [comment]
@halton 
it's updated. thx.

**Comment by halton** [comment]
Still show me conflicts.

**Comment by PeterWangIntel** [comment]
@halton 
sorry, can you try to merge the new patch

**Pull request merged**
