### PR TITLE
[Android] Fix the null pointer issue.

### PR DESCRIPTION
**Pull request by wuhengzhi**
Press the back key continually when launches application, sometimes it
will lead to crash with null pointer.

BUG=XWALK-4778

### CODE REVIEW

**Comment by wuhengzhi** [comment]
@halton PTAL, thanks.

**Comment by halton** [comment]
Does this PR related with XWALK-4778? If not, please remove the line.

**Comment by wuhengzhi** [comment]
Yes, it's a bug in XWALK-4778.

**Comment by halton** [comment]
LGTM and merging.

**Comment by Cy-Bo-Rg** [comment]
awesome job guys :)

**Pull request merged**
