### PR TITLE
[Android] Implement the text zoom API.

### PR DESCRIPTION
**Pull request by wuhengzhi**
This patch is to implement API for setTextZoom() and getTextZoom().
Adjust test case for reuse.
Add test case for setTextZoom() and getTextZoom().

BUG=XWALK-4994

### CODE REVIEW

**Comment by axinging** [comment]
Thanks hengzhi's quick fix!
I have two comments for this:
1), I think no need to export these API through XWalkView. Cause XWalkSettings will be public soon. For this, you may refer to @lincsoon.
2), Please also help to implement the following API(It's my fault. I tried to add the following API in the bug description. But seems not succeed.)
setDefaultFontSize(size);
setDefaultFixedFontSize(size);
size:a non-negative integer between 1 and 72 ， The default is 16

**Comment by wuhengzhi** [comment]
1. I will communicate with @lincsoon  next Monday.
2. I will implement the APIs in another PR.
Thanks.

**Comment by lincsoon** [comment]
This PR is still available. Let's just wait for XWalkSettings

**Comment by wuhengzhi** [comment]
The APIs about default font size has been implemented, I will rebase it when XWalkSettings was exposed.

**Comment by wuhengzhi** [comment]
@axinging @lincsoon @XiaosongWei @xzhan96 @fujunwei PTAL, thanks.

**Comment by lincsoon** [comment]
LGTM

**Comment by fujunwei** [comment]
LGTM

**Comment by xzhan96** [comment]
LGTM

**Pull request merged**
