### PR TITLE
[Android] Open web pages in default browser instead of in-app browsing.

### PR DESCRIPTION
**Pull request by gaochun**
Pages linked with <a target="_blank"> or windowd.open() will be opened
in system default browser.

BUG=https://crosswalk-project.org/jira/browse/XWALK-1037

### CODE REVIEW

**Comment by ricardo85x** [comment]
with the xwalk_core_library_beta:13.42.319.6
the <a target="_blank" href="http://www.google.com.br" >BLANK</a>
is not working.

but the <span onclick="open('http://www.google.com')"> popup </span>

is working fine.

**Comment by halton** [comment]
@gaochun this PR seems long time no update, still valid?

**Comment by halton** [comment]
@ricardo85x target=blank is supposed to be disable by PR by @DonnaWuDongxia . We exposed a embeding API to override that behavior, please ping @lincsoon for that.

**Comment by lincsoon** [comment]
This PR is overwrote by #2947. Please override the XWalkUIClient.onCreateWindowRequested for the "target=_blank" links.

**Comment by ricardo85x** [comment]
Hi @lincsoon.
I am using org.xwalk:xwalk_core_library_beta:14.43.343.1
and I did overwrite the OnCreateWindowRequest.
But I can't find the url of the link when this method run.

**Comment by ricardo85x** [comment]
I just find out using this release: beta:14.43.343.1

the all links open inside the current view.

**Comment by lincsoon** [comment]
@ricardo85x sorry for late response. 

First, you need to set XWalkPreferences.SUPPORT_MULTIPLE_WINDOWS to true. Second, the new link must be "taget=_blank", or it will be opened in the current view. 

Since here is not the right place to discuss issues outside the commit, if still doesn't work, please create an issue on JIRA(https://crosswalk-project.org/jira/secure/Dashboard.jspa), and illustrate your sample code and the web page you tested with.

**Pull request merged**
