### PR TITLE
[Android] Add two parameters for ClientCertRequest.

### PR DESCRIPTION
**Pull request by wuhengzhi**
Add principals and KeyTypes for ClientCertRequest, provide two
APIs to get principals and key types.
Refine the test case for ClientCertRequest.

BUG=XWALK-6025

### CODE REVIEW

**Comment by wuhengzhi** [comment]
@lincsoon @axinging @fujunwei @xzhan96 @XiaosongWei PTAL, thanks.

**Comment by fujunwei** [comment]
LGTM.

**Comment by wuhengzhi** [comment]
ping @lincsoon @axinging @xzhan96 @XiaosongWei, thanks.

**Comment by lincsoon** [comment]
LGTM

**Pull request merged**
