### PR TITLE
Just use id instead of calling host->GetID() again

### PR DESCRIPTION
**Pull request by mrunalk**
simple fix

### CODE REVIEW

**Comment by rakuco** [comment]
What is it supposed to fix? Is there a related ticket?

**Comment by mrunalk** [comment]
It's just a simple optimization I noticed while working on Print feature.

**Comment by rakuco** [comment]
While there's nothing wrong with the idea, the new code will break the build if NaCl is disabled. For example, I do my Linux builds with `component=shared_library disable_nacl=1` and get this with your patch:

```
../../xwalk/runtime/browser/xwalk_content_browser_client.cc:171:7: error: unused variable 'id' [-Werror,-Wunused-variable]
  int id = host->GetID();
```

**Comment by mrunalk** [comment]
Agreed, not worth it then.

**Pull request closed without merging**
