### PR TITLE
To disable WebNotification for Crosswalk for Android

### PR DESCRIPTION
**Pull request by PeterWangIntel**
Building with "-Ddisable_notifications=1" reduces size by 68K.

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@d0ngjun
It's the clean patch cherry-picked to crosswalk-lite branch.

**Comment by d0ngjun** [comment]
This patch need rebase.

**Comment by halton** [comment]
@PeterWangIntel seems the trybot fail on same error again, could you check?

**Comment by halton** [comment]
@d0ngjun please continue your review. @PeterWangIntel please force update to trigger the trybot.

**Comment by d0ngjun** [comment]
LGTM

**Comment by PeterWangIntel** [comment]
@halton, trybot is failed just because it's one parts of the parts located in three repos. Please merge this patch, since the corespondent part in 'chromium' is merged already.

**Comment by halton** [comment]
@PeterWangIntel please rebase so that I can merge.

**Comment by halton** [comment]
@PeterWangIntel please push again to see whether the gclient sync issue still there.

**Comment by PeterWangIntel** [comment]
@halton, it works now. 
there are two sequent patches now: one for disabling notification, another one is to update the DEPS.xwalk so that trybot can aware of the corespondent commits in blink and chromium for disabling notification.

**Comment by PeterWangIntel** [comment]
@halton

**Comment by halton** [comment]
LGTM, merging.

**Pull request merged**
