### PR TITLE
Xwalk 6276 lint error

### PR DESCRIPTION
**Pull request by wuhengzhi**
Enable "chromium_code", fix lint warnings.

### CODE REVIEW

**Comment by wuhengzhi** [comment]
Compile failed since the PR for Blink was not submitted.

**Comment by wuhengzhi** [comment]
@rakuco @lincsoon @fujunwei @XiaosongWei @xzhan96 @kenny-y @axinging PTAL, thanks a lot.

**Comment by wuhengzhi** [comment]
Chromium side: https://github.com/crosswalk-project/chromium-crosswalk/pull/324

**Comment by axinging** [comment]
LGTM.  I am looking forward to this happens.
Note, there will be a back door for UnusedResources.

Some background:
http://developer.android.com/tools/debugging/improving-w-lint.html
http://tools.android.com/tips/lint/suppressing-lint-warnings

**Comment by rakuco** [comment]
Thanks for the patch, I'll try to take a look at this now that the V8+M49 situation is hopefully resolved.

**Comment by rakuco** [comment]
OK, this pull request is *huge*, we need to split it up.

Most of the warnings are not really that important; I'm more concerned about the `NewApi` lint warnings that indicate we're using API that is not available on all devices we support.

Does this PR address this problem (I remember you were talking about the Presentation API code in JIRA)? All the rest can wait and be done later.

**Comment by rakuco** [comment]
(See also my recent comments in XWALK-6276 and the newly-created XWALK-6495)

**Comment by wuhengzhi** [comment]
Yes, this PR also address the `NewApi` warnings.
In XWalkViewShellActivity.java, `android.app.ActionBar.Tab` was deprecated, the material design was encouraged to use. About this situation, it's not the kernel code, so I just suppress the warnings with `@SuppressWarnings("deprecation")`. What's your opinion?
I will split this PR for `NewApi`.

**Pull request closed without merging**
