### PR TITLE
[Android] Change the order of XWalkHitTestResultInternal

### PR DESCRIPTION
**Pull request by chuan9**
Refine embedding API getHitTestResult

Change the order of XWalkHitTestResultInternal in reflection_generator.py

BUG=XWALK-6878

### CODE REVIEW

**Comment by chuan9** [comment]
@lincsoon Please have a review

**Comment by xzhan96** [comment]
BUG=XWALK-6678? Please double check.

**Comment by chuan9** [comment]
Changed it already, thanks

**Comment by chuan9** [comment]
@lincsoon Please have a review, thanks

**Comment by lincsoon** [comment]
I can't see any change of the commit log

**Comment by chuan9** [comment]
@lincsoon Added the blank line before bug number as you said, I can see the changes

**Comment by xzhan96** [comment]
You need modify the file locally and then `git push -f ` again instead of just change the contents in this PR.
I see this commit message is

> 
[Android] Change the order of XWalkHitTestResultInternal
in reflection_generator.py

> BUG=XWALK-6878

It's should not your real purpose, right?

**Comment by chuan9** [comment]
@xzhan96 Got it, already change the commit log, thanks

**Pull request merged**
