### PR TITLE
[Android] Shared mode implementation

### PR DESCRIPTION
**Pull request by lincsoon**
Shared mode allows multiple xwalk apps to share one xwalk runtime
library. Each xwalk app is bundled with a reflection layer instead
of the whole runtime library, whereas there is a library apk to be
installed on device for xwalk apps to use.

BUG=XWALK-2948

### CODE REVIEW

**Comment by lincsoon** [comment]
On the basis of #2780 , this patch fixed error of instrumentation test. Please see original pull request to check reviews and discussions.

**Comment by halton** [comment]
@lincsoon could you mark the delta change to fix the testing issue? Thus will save reviewer time.

**Comment by lincsoon** [comment]
@halton I separate original patch to 2 commits. Please help to reivew

**Comment by lincsoon** [comment]
The reflection layer will be initialized before all things on both of embedded mode and shared mode. But in test of XWalkCoreInternalShell, this step is skipped because there's no reflection layer. In this case, the instance of XWalkCoreBridge is null.

**Comment by halton** [comment]
LGTM

**Comment by rakuco** [comment]
Thank you for acting so promptly. Could you please re-squash the commits together? If that's not done, we will have one commit in the tree that is knowingly bootleg and make bisecting and reverting more difficult.

**Comment by rakuco** [comment]
:+1:

**Comment by lincsoon** [comment]
Thanks for everybody's quick response!

**Pull request merged**
