### PR TITLE
[Android] Fix the warnings when generating java docs

### PR DESCRIPTION
**Pull request by lincsoon**
This patch completes the method's descriptions that are missing the
field @param or @return.

BUG=XWALK-5643

### CODE REVIEW

**Comment by lincsoon** [comment]
@rakuco @xzhan96 @fujunwei Please help to review

**Comment by xzhan96** [comment]
lgtm

**Comment by rakuco** [comment]
Remember to mention XWALK-5643.

**Comment by rakuco** [comment]
lgtm

**Pull request merged**
