### PR TITLE
Move to Chromium 41.0.2272.16.

### PR DESCRIPTION
**Pull request by rakuco**
This is the first Chromium beta release of the M41 milestone.

Major Chromium CLs and bugs that caused the code to be changed:

* The classes have been updated to follow Google's C++ style guide and
  only use one of {virtual,final,override} in declarations, to make the
  build work with Chromium's clang and its style plugin.

* Chromium bug 421063 (several CLs).
  By default, V8's initial snapshot will now be loaded from external
  files, called natives_blob.bin and snapshot_blob.bin. We need to copy
  them to our assets like we do with xwalk.pak and icudtl.dat.

* Changes to the notification API:
  - https://codereview.chromium.org/774573003
  - https://codereview.chromium.org/776813004
  - https://codereview.chromium.org/794633002

  content::ContentBrowserClient's CheckDesktopNotificationPermission()
  and ShowDesktopNotification() methods were removed and a new class
  called content::PlatformNotificationService is now responsible for
  basically the same tasks.

  Our implementation, XWalkPlatformNotificationService, contains pretty
  much the same implementation we had for those methods which got
  removed, modulo the required API changes caused by
  content::PlatformNotificationData's members being different from
  content::ShowDesktopNotificationHostMsgParams.

  The new methods for handling persistent notifications (Chromium bug
  432527) are currently no-ops waiting for an implementation.

* Changes to the Vibration API code in the content layer.
  The Tizen code needs to be adjusted after
  https://codereview.chromium.org/583663003 changed the Chromium side
  considerably.
  Tracking bug: XWALK-3398.

* gyp_xwalk is in sync with gyp_chromium at df96803.

Additionally, the code also had to take the following Chromium CLs into
account:

* https://codereview.chromium.org/109433013
* https://codereview.chromium.org/812353003
* https://codereview.chromium.org/728923002
* https://codereview.chromium.org/691823002
* https://codereview.chromium.org/794633002
* https://codereview.chromium.org/680943002
* https://codereview.chromium.org/741753002
* https://codereview.chromium.org/691863002
* https://codereview.chromium.org/790423002
* https://codereview.chromium.org/652363005
* https://codereview.chromium.org/734263003
* https://codereview.chromium.org/393133002
* https://codereview.chromium.org/737133006
* https://codereview.chromium.org/577363002
* https://codereview.chromium.org/808573003
* https://codereview.chromium.org/723633003
* https://codereview.chromium.org/721273002

### CODE REVIEW

**Comment by rakuco** [comment]
@darktears

**Comment by darktears** [comment]
LGTM

**Comment by rakuco** [comment]
crap on a catapult (tm)
the Android failures are real, the code now assumes depot_tools is up-to-date enough to fetch gsutil 4.7, I need to add a .boto file with the proxy settings.

**Comment by rakuco** [comment]
YES!!!!!!11111111111

**Pull request merged**
