### PR TITLE
Port the update of shared mode to crosswalk-14

### PR DESCRIPTION
**Pull request by lincsoon**

### CODE REVIEW

**Comment by lincsoon** [comment]
@rakuco Please help to merge

**Comment by lincsoon** [comment]
Fixed test error of XWalkRuntimeClient

**Comment by lincsoon** [comment]
@rakuco

**Comment by lincsoon** [comment]
@rakuco This patch is needed by Cordova Plugin. Please help to merge if there's no problem

**Comment by rakuco** [comment]
Hi Lin,

I'm still a bit confused as to whether this is a required bug fix for the beta branch or if it's just introducing new features/making some of the code easier to use. In case it's the latter, isn't there a way to fix the cordova plugin part instead so that it does not need this PR?

**Comment by lincsoon** [comment]
Hi Raphael,

These patches are neither new features nor bug fixes, they are just infrastructure support for Cordova Plugin. We've already discussed the implementation, this is final solution and there no other alternatives.

**Comment by rakuco** [comment]
OK. I feel a bit wary of merging a 1500-line patch at this point in crosswalk 14's lifecycle, but I trust your judgement on this one.

**Comment by baleboy** [comment]
This feature missed the 14 deadline by quite a bit. I recommend that we postpone it to 15

**Comment by rakuco** [comment]
Plus it broke the build, see XWALK-4746.

**Comment by baleboy** [comment]
As agreed in our sync meeting today, this PR should be reverted.

**Comment by lincsoon** [comment]
Sorry, I have other thought about this issue. I will raise a mail to discuss it.

**Pull request merged**
