### PR TITLE
[Android] Improve the prompt message of shared mode

### PR DESCRIPTION
**Pull request by lincsoon**
Prompt the user explicitly to restart the app after installed the
Crosswalk Project runtime.

### CODE REVIEW

**Comment by lincsoon** [comment]
@baleboy @rakuco

**Comment by baleboy** [comment]
I couldn't tell if this also changes the dialog title to "<app name> requires the Crosswalk Project Runtime". If it does, LGTM, otherwise please add it.

**Comment by lincsoon** [comment]
Done!

**Comment by lincsoon** [comment]
Can we merge this PR?

**Pull request merged**
