### PR TITLE
[Lite] Disable WebDatabase.

### PR DESCRIPTION
**Pull request by heke123**
38K binary size reduced.  
Add flag 'disable_webdatabase'

### CODE REVIEW

**Comment by heke123** [comment]
@PeterWangIntel  @halton   Pls help to review, thanks.

**Comment by heke123** [comment]
@halton , rebase done

**Comment by PeterWangIntel** [comment]
LGTM

**Comment by heke123** [comment]
@halton  Please help to review and merge. thanks.

**Pull request merged**
