### PR TITLE
sysapps: Rewrite the check for UDPSocket::SendTo's return value.

### PR DESCRIPTION
**Pull request by rakuco**
Drop the check for whether it has returned the number of bytes we are
trying to send (which includes a comparison between a size_t and an
int) since it does not make much sense. We only need to contemplate 3
different cases:

1. SendTo returns ERR_IO_PENDING, which means it is still transmitting
   all the data.
2. SendTo returns another negative value, so we just bail out.
3. SendTo returns a positive value, which means everything was
   transmitted, otherwise ERR_IO_PENDING would have been returned.

### CODE REVIEW

**Comment by rakuco** [comment]
@darktears @heke123

**Comment by darktears** [comment]
LGTM

**Comment by heke123** [comment]
LGTM
I don't think base::checked_cast is unacceptable, Line 270 has another base::checked_cast.

**Comment by rakuco** [comment]
Nobody said it's unacceptable, it's just unnecessary if the code can be rewritten in a more clear manner.

**Pull request merged**
