### PR TITLE
Lzma backport

### PR DESCRIPTION
**Pull request by d0ngjun**
This involve 2 commits here:

1. LZMA compression support
   Use lzma compress libxwalkcore.so to reduce apk size.
This feature is backport from lite.

2. add support for runtime build flag.
    Add --enable_lzma parameter into make_apk.py:
    True: compress the libxwalkcore.so into libxwalkcore.so.$arch, then move it into apk's res/raw directory.
    False: do not compress libxwalkcore.so (default behavior).
Besides, also include some refactor work, for the shared-mode/embedded mode/embedded mode with lzma support is too much complicated when they involved in one script.

@halton @shawngao5 @lincsoon please help review, thanks!

### CODE REVIEW

**Comment by darktears** [comment]
Do this includes a way for use to customized the "Uncompressing" screen?

**Comment by kenchris** [comment]
@darktears you mean that a uncompressing screen will be shown? Is it not possible to do so as part of the install process?

**Comment by darktears** [comment]
Yes there is a screen shown on the first launch. I don't think you can hook up something when an APK is installed, so we need to uncompress at first run.

**Comment by halton** [comment]
> Yes there is a screen shown on the first launch. I don't think you can hook up something when an APK is installed, so we need to uncompress at first run.

Thanks for @darktears 's explanation. This is correct.

> Do this includes a way for use to customized the "Uncompressing" screen?

Yes, this is a future feature which is tracked in https://crosswalk-project.org/jira/browse/XWALK-3475

**Comment by kenchris** [comment]
ok lgtm then

**Comment by darktears** [comment]
This broke Windows badly in the python code. `file` and `tar` commands do not exist. We should leverage python infrastructure when possible.

**Pull request merged**
