### PR TITLE
M52: fix tcp and udp socket compilation failures

### PR DESCRIPTION
**Pull request by msisov**

### CODE REVIEW

**Comment by rakuco** [comment]
@mrunalk

**Comment by rakuco** [comment]
@msisov: it's good practice to indicate the upstream CL numbers that caused these changes here (see the other commits in the branch for examples).

**Comment by mrunalk** [comment]
@msisov Please add the references to upstream commits so that we know the reasoning behind these changes. For example see this, e39883830516640d8c6230f7a22f6490949dda4a. Almost 99% of the times you can trace the errors to upstream changes.

**Comment by mrunalk** [comment]
I have merged your changes into next for now as I needed to proceed. I was going to add upstream commit info myself but didn't have much time to look that up. If you can list those upstream commits here by replying to this thread, that will be great. I will use that information later. Otherwise it's good to see you making progress. I have fixed the Linux build now so you can move on to Android next.

**Pull request closed without merging**
