### PR TITLE
Shared library check using PackageManager

### PR DESCRIPTION
**Pull request by terriko**
This is a reworking of https://github.com/crosswalk-project/crosswalk/pull/2718.  In order to avoid the licensing issue, this makes the assumption that the PackageManager is trustworthy and checks that signature.

### CODE REVIEW

**Comment by baleboy** [comment]
Is this still required for the shared mode implementation, or was it replaced by another PR? @terriko @lincsoon

**Comment by terriko** [comment]
I assumed that @lincsoon will be rolling it into a more comprehensive patch with actual signature checks, but I can clean this up so it's mergable if needed.

**Comment by baleboy** [comment]
that might be the case, the overall patch about shared mode is https://github.com/crosswalk-project/crosswalk/pull/2780, let's wait for @lincsoon to comment

**Comment by lincsoon** [comment]
Because this PR is based on old implementation, I already prepared another patch upon the approach from Terri in my new implementation of shared mode. As #2780 has been merged, I will soon send the PR about security check.

**Comment by terriko** [comment]
Excellent, this can be closed then.

**Pull request closed without merging**
