### PR TITLE
[Tizen] Fix order of default widget start files

### PR DESCRIPTION
**Pull request by sstolinski**
This patch fixes improper order of default widget entry pages.

### CODE REVIEW

**Comment by pozdnyakov** [comment]
lgtm

**Comment by sstolinski** [comment]
Commit message corrected.

**Comment by rakuco** [comment]
Can you expand the commit message a bit more? This looks like the same fix from aae1f929200f8f166e4f88ae8cd3a84a010c0a1d applied elsewhere in the code; if that's the case, mentioning that the W3C Widget spec specifies a certain order just like the other commit message does is a good idea.

**Comment by sstolinski** [comment]
@rakuco It is almost the same fix, but the code from https://github.com/crosswalk-project/crosswalk/commit/aae1f929200f8f166e4f88ae8cd3a84a010c0a1d is now deleted by https://github.com/crosswalk-project/crosswalk/commit/916d78dabd6ff1befd4c23dc1c3d37acbc95a52c.

**Pull request merged**
