### PR TITLE
[Tizen] Remove support of Tizen.

### PR DESCRIPTION
**Pull request by darktears**
There may be some following patches to remove more
(e.g. support of the widget spec).

### CODE REVIEW

**Comment by darktears** [comment]
@poussa @baleboy @pozdnyakov @rakuco 

We may have some following cleanups but I guess the big part is here.

**Comment by poussa** [comment]
LGTM. Enjoy the green button click.

**Comment by rakuco** [comment]
yes!

**Comment by rakuco** [comment]
I'll take a more in-depth look on Monday. @joone: please take a look too, you mentioned there's some ozone-wayland code under Tizen ifdefs that is not really Tizen-specific.

In any case:
rupaul

**Comment by rakuco** [comment]
There are too many changes for GitHub to display, so I need to comment manually here:

* build/system.gyp:
```
-      'conditions': [
-        ['building_crosswalk_bin==1', {
-          'direct_dependent_settings': {
-            'cflags': [
-              '<!@(pkg-config --cflags <(glib_packages))',
-            ],
-          },
-          'link_settings': {
-            'ldflags': [
-              '<!@(pkg-config --libs-only-L --libs-only-other <(glib_packages))',
-            ],
-            'libraries': [
-              '<!@(pkg-config --libs-only-l <(glib_packages))',
-            ],
-          },
-        },
-       ],
-      ],
```
These lines shouldn't be removed, but just moved out of the `building_crosswalk_bin` check, just like you did for the libnotify part.

**Comment by rakuco** [comment]
Please also remember to remove `.gbp.conf` from the root of the source tree.

**Comment by pozdnyakov** [comment]
RS=me

**Comment by darktears** [comment]
Fixed the comments.

@baleboy we're waiting your green flag.

**Comment by baleboy** [comment]
LGTM!

**Comment by jeez** [comment]
LGTM  ;)

**Comment by lpereira** [comment]
LGTM as well. :)

**Comment by ricardotk** [comment]
Looks awesome to me (:

**Comment by baleboy** [comment]
To be clear support is not removed but rather moved to https://github.com/crosswalk-project/crosswalk-tizen

**Pull request merged**
