### PR TITLE
[Lite] To disable Web Bluetooth

### PR DESCRIPTION
**Pull request by PeterWangIntel**
Reduced size = 20K

### CODE REVIEW

**Comment by PeterWangIntel** [comment]
@heke123 @halton

**Comment by PeterWangIntel** [comment]
The pair patches are 
https://github.com/crosswalk-project/chromium-crosswalk/pull/291
https://github.com/crosswalk-project/blink-crosswalk/pull/89

**Comment by heke123** [comment]
LGTM

**Comment by halton** [comment]
Please bump DEPS.xwalk

**Pull request merged**
