### PR TITLE
[Android] Fixed XWalkPreference error before xwalk is ready

### PR DESCRIPTION
**Pull request by lincsoon**
Fixed the error that only last setValue works when calling setValue
multiple times before xwalk is ready.

BUG=XWALK-4868

### CODE REVIEW

**Comment by lincsoon** [comment]
This PR fixes the remote debugging issue

**Comment by lincsoon** [comment]
@fujunwei @axinging @halton Please help to review

**Comment by halton** [comment]
@lincsoon The code change to me is simple reduce code by introduce `sReservedActions` to substitute sReservedObjects, sReservedClass and sReservedMethods.

I can not understand which part is the key fixing for the issue "only last setValue works when calling setValue multiple times before xwalk is ready."

**Comment by lincsoon** [comment]
The key is in line 51. I make a deep copy of arguments for each reserved methods. The second change is that the actions will be re-invoked exactly in the order that they are reserved. In previous implementation, the order is `create instance` -> `static class` -> `invoke method`

**Comment by halton** [comment]
LGTM, will merge.

**Pull request merged**
