### PR TITLE
Wifi Direct Experimental API initial contribution

### PR DESCRIPTION
**Pull request by astojilj**
First implementation supports Android. Windows support under work.
Manual test ready to be deployed to crowwsalk-test-suite/usecase
Mock test to be developed after and contributed here - added entries to test gyp files.

### CODE REVIEW

**Comment by astojilj** [comment]
@alexshalamov Please help to review. thanks.

**Comment by halton** [comment]
@jondong would you please review this PR since you're doing the presentation for Android.

@astojilj Could you add the spec link and version you're following?

**Comment by astojilj** [comment]
@jondong thanks. updated.
@halton No spec on this yet. No interest for this API in Chrome OS.
Adding Windows support and tests before negotiating with Chrome OS - at which point spec would come.

**Comment by astojilj** [comment]
Do you have an estimate, when could this get integrated? I think that I don't have submit rights. Thanks

**Comment by halton** [comment]
LGTM and merging.

**Pull request merged**
