### PR TITLE
unable to play some mp4 file

### PR DESCRIPTION
**Pull request by myselfgaurav**
hi unable to play some mp4 files using crosswalk browser,

i made screenshot video from my android device , it is not even player by default android player , so i think crosswalk browser is unable to play it , but my issue is that i can use other player to play that file like mx player and other , is there any way that file vidoe file would play

### CODE REVIEW

**Comment by halton** [comment]
@myselfgaurav are you not submit changes to review? If you are trying to report issue, please use https://crosswalk-project.org/jira/

**Comment by js0701** [comment]
Hi gaurav,

Crosswalk (and Chromium) is using Android Media Play service for video playback,. If default media player can't play it, Crosswalk won't be able to play it.

**Comment by myselfgaurav** [comment]
is there any way to play that file as it mp4 and play in desktop chrome
player easliy ,

**Comment by halton** [comment]
Again, pull request is not place to discuss issues. It is only for patch review. I'm going to close it.

**Pull request closed without merging**
