### PR TITLE
[Android] Add support disabling copy/paste in XWalkView

### PR DESCRIPTION
**Pull request by XiaosongWei**
Delegate ContentView's performLongClick() to XWalkView so that developer
can override XWalkView's performLongClick() or setOnLongClickListener() to
disable copy/paste action bar.
A new annotation XWalkAPI.delegate is used to ensure that the callback
from XWalkViewInternal to XWalkView is one-way and the actual implementation
of callback in XWalkView side is specified via XWalkAPI.preWrapperLines.

BUG=XWALK-4786

### CODE REVIEW

**Comment by SandroGrzicic** [comment]
We assume that after this PR is merged, the following code will start working if added at the end of the onCreate method in MainActivity.java in a Cordova application:

        super.appView.getView().setOnLongClickListener(new View.OnLongClickListener() {
            public boolean onLongClick(View v) {
                return true;
            }
        });
        super.appView.getView().setLongClickable(false);

If so, thanks for the PR, hopefully a version with this commit will be published soon. This is obviously a critical issue since it completely messes up the app when the long-click menu is opened.

**Comment by XiaosongWei** [comment]
@lincsoon @axinging @halton

**Comment by XiaosongWei** [comment]
@SandroGrzicic Yes, the LongClick handling code should work as expected after this PR's merged.

**Comment by axinging** [comment]
This introduce a new API "onPerformLongClick". Is it possible to use any API of View or XWalkView to do this?

**Comment by XiaosongWei** [comment]
@axinging No. actually the onPerformLongClick in XWalkView is private, it's just used for XWalkViewInternal/Bridge to call into XWalkView/View's performLongClick().

**Comment by axinging** [comment]
LGTM

**Comment by wmfairuz** [comment]
Does this is available in current release of Crosswalk? Thanks

**Comment by halton** [comment]
@wmfairuz should available almost half year ago, any bug you meet?

**Comment by freedomofkeima** [comment]
I've just wanted to ask the same thing. In the [stable version](https://crosswalk-project.org/documentation/downloads.html) (15.44.384.12), I could not find this feature. Which version is this feature introduced in?

**Comment by halton** [comment]
Refer to https://github.com/crosswalk-project/crosswalk-website/wiki/Release-dates, this feature at least integrated in Crosswalk-16

**Comment by matikbird** [comment]
I can't reproduce this..```

public class MainActivity extends CordovaActivity {
    private static final String TAG = MainActivity.class.getSimpleName();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Set by <content src="index.html" /> in config.xml
        loadUrl(launchUrl);

        // disable the context menu and all long clicks
             super.appView.getView().setOnLongClickListener(new View.OnLongClickListener() {
        public boolean onLongClick(View v) {
            return true;
        }
    });
    super.appView.getView().setLongClickable(false);
    }
}
```

> Error: /home/matikbird/Textile/platforms/android/gradlew: Command failed with exit code 1 Error output:
> /home/matikbird/Textile/platforms/android/src/com/Textile/MainActivity.java:34: error: package View does not exist
>              super.appView.getView().setOnLongClickListener(new View.OnLongClickListener() {
>                                                                     ^
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 error

Any clues?
Thanks in advance, I've searched the whole web..
I want to select the text, but the Contextual Action Bar is messing things up.

**Comment by matikbird** [comment]
I would really appreciate any help on this. Please.

**Comment by halton** [comment]
@wmfairuz if you could report a [JIRA] (https://crosswalk-project.org/jira) issue with crosswalk version and test case, that would be more efficient.

**Comment by matikbird** [comment]
https://crosswalk-project.org/jira/browse/XWALK-7206

Done.

**Comment by matikbird** [comment]
(done filling the issue. i'm not done with the issue. i'm losing it, @halton)

**Comment by halton** [comment]
@matikbird see the report, let's move conversation there.

**Comment by matikbird** [comment]
I moved everywhere, I'm about to send it to the newspaper.

But @SandroGrzicic seems like he solved the issue. I even stalked the guy on FB and send him a message, like any rational person would do.

**Comment by matikbird** [comment]
I had a conversation with @SandroGrzicic and apparently, this is about versions.

He told me that he successfully disabled the Contextual Action Bar using Crosswalk Beta 17.

I tried that. Tried 18, 19, 20, 21, 22, 23, 16, and none of them work.
Can someone reproduce this and disable it?


```
package com.myApp;

import android.os.Bundle;
import org.apache.cordova.*;
import android.view.View;
public class MainActivity extends CordovaActivity {
    private static final String TAG = MainActivity.class.getSimpleName();


    @Override
      public void onCreate(Bundle savedInstanceState) {
        
      super.onCreate(savedInstanceState);
      loadUrl(launchUrl);
   super.appView.getView().setOnLongClickListener(new View.OnLongClickListener() {
        public boolean onLongClick(View v) {
            return true;
        }
    });
    super.appView.getView().setLongClickable(false);
}
}

```

package com.Textile;

import android.os.Bundle;
import org.apache.cordova.*;
import android.view.View;
public class MainActivity extends CordovaActivity {
    private static final String TAG = MainActivity.class.getSimpleName();


    @Override
      public void onCreate(Bundle savedInstanceState) {
        
      super.onCreate(savedInstanceState);
      loadUrl(launchUrl);
   super.appView.getView().setOnLongClickListener(new View.OnLongClickListener() {
        public boolean onLongClick(View v) {
            return true;
        }
    });
    super.appView.getView().setLongClickable(false);
}
}

```

It works, it builds, but the contextual bar still shows up.
I tried different versions of the Android SDK (you never know)..
    <preference name="android-minSdkVersion" value="14" />
    <preference name="android-targetSdkVersion" value="19" />
    <preference name="xwalkVersion" value="18+" />

Same result..

**Pull request merged**
