### PR TITLE
[Android] Update new shouldInterceptRequest usage sample

### PR DESCRIPTION
**Pull request by xzhan96**
As new shouldInterceptRequest has been implemented, the usage sample
also need to be updated.

BUG=XWALK-5956

### CODE REVIEW

**Comment by xzhan96** [comment]
@fujunwei @wuhengzhi @lincsoon @XiaosongWei @axinging 
please help review.

**Comment by wuhengzhi** [comment]
LGTM, thanks.

**Comment by xzhan96** [comment]
@fujunwei @lincsoon @XiaosongWei @axinging 
Please help to review

**Comment by xzhan96** [comment]
As XWalkWebResourceResponseInternal will also used by xwalk core, so it needs a tag "createInternally = true", which means reflection script would not reflect its parameters, so the constructor of XWalkWebResourceResponse.java is XWalkWebResourceResponse(Object bridge), so the application can't use it.

**Comment by xzhan96** [comment]
@fujunwei  @lincsoon  @axinging please help to review, thanks

**Comment by fujunwei** [comment]
The expose API and call by native should  be independent of each other in the XWalkWebResourceResponseInternal.java ?

**Comment by xzhan96** [comment]
sure, I already separate the expose API and call by native function in XWalkWebResourceResponseInternal.java

**Comment by fujunwei** [comment]
Do you mean we can use `new XWalkWebResourceResponse` after your reorganization?

**Comment by xzhan96** [comment]
No, they are the different thing.
I see what's you mean, you want 1 more file to just reflect API to user, so that application can use "new XWalkWebResourceResponse", right? 
I tried this way before, but not successful, I forget the root cause.
I think I can do it again to get this purpose when I have time, this API update is just for current implementation.

**Comment by xzhan96** [comment]
@lincsoon could you help to review?

**Pull request merged**
