### PR TITLE
[Android] Fixed crash errors of shared mode

### PR DESCRIPTION
**Pull request by lincsoon**
* Fixed crash when initializing embedded mode by default
* Fixed crash when launching XWalkCoreShell under lite mode
* Support setUIClient and setResourceClient before Crosswalk runtime
  is ready
* Associate XWalkInitializer and XWalkUpdater to each single activity

BUG=XWALK-4072, XWALK-4388, XWALK-4503

### CODE REVIEW

**Comment by lincsoon** [comment]
@d0ngjun Please help to review

**Comment by d0ngjun** [comment]
LGTM

**Comment by halton** [comment]
@lincsoon okay to merge?

**Comment by lincsoon** [comment]
Yes, please

**Pull request merged**
