### PR TITLE
[Android] Use SurfaceView as XWalkView's default render backend.

### PR DESCRIPTION
**Pull request by axinging**
SurfaceView provids better performance for application which does not need animating the XWalkView. So we use it as default.

BUG=XWALK-4366

### CODE REVIEW

**Comment by rakuco** [comment]
@baleboy: if this gets in it must be in the release notes so people are aware of possible changes in their apps.

**Comment by axinging** [comment]
@lincsoon @fujunwei @kenchris @darktears @halton

**Comment by fujunwei** [comment]
LGTM, thanks.

**Comment by halton** [comment]
@axinging you need update https://github.com/axinging/crosswalk/blob/xwalk-4366-surfaceviewdefault/runtime/android/core_internal/src/org/xwalk/core/internal/XWalkPreferencesInternal.java#L80 so that javadoc can be updated automatically.

**Comment by axinging** [comment]
Thansk @halton. Updated.

**Comment by halton** [comment]
LGTM, merging.

**Comment by jonathanewerner** [comment]
May i ask when we might we able to expect this in beta / core versions? 
Thank you. :)

**Comment by rakuco** [comment]
This commit was only merged to the master branch (Crosswalk 15), and has been present in canaries ever since.
It will make it into betas once we deem Crosswalk 15 OK to be promoted to the beta channel (our schedule has slipped a bit because of all the summer holidays).

**Pull request merged**
