### PR TITLE
Remove messaging, contacts and device capabilities SysApps API

### PR DESCRIPTION
**Pull request by tingshao**
Those API extensions are not needed anymore and should be removed.

BUG=XWALK-6875
@halton

### CODE REVIEW

**Comment by tingshao** [comment]
In XWalkExtensionsIFrameTest.CrossContextsReferenceShouldNotCrash testcase, call fs sysapp API to verify the cross context reference instead of the removed device capability API.
@halton

**Comment by halton** [comment]
LGTM, @rakuco before I merge this PR, any concerns? CC @baleboy

**Comment by baleboy** [comment]
Basically this is fine, but could you list the APIs that are being removed? I'd like to send a deprecation email with the details.

**Comment by tingshao** [comment]
@baleboy 
Only contacts, messages and device capability are removed.
others are kept, for example, the storage api is used by our realsense extension.

**Pull request merged**
