### PR TITLE
Refactor to remove duplicated code after Presentation API is re-implemented on Android

### PR DESCRIPTION
**Pull request by kenny-y**
Note: Fixed Windows build of the previously reverted one.

Refactor to remove duplicated code after Presentation API is re-implemented on Android

Prior to XWALK-4646, there was the impl. of W3C presentation API for Windows platform. It was Windows-only impl at that time.

After some experiment, there was a common subset identified in source code between Android & Windows platform impl., but considering the fact that XWALK-4646 was in high priority (P1 blocker) at that time, and I was unable to obtain a Windows box to test the modified behavior on Windows, I made a decision to copy the common code and modify part of it to Android-specific source code.

After XWALK-4646 is resolved, this XWALK-6262 was opened to track the leftover task, which is to share the common code between Windows & Android platform. It was delayed due to rebase and other resource issues. Now it's finally done.

BUG=XWALK-6262

### CODE REVIEW

**Comment by kenny-y** [comment]
Sorry for this late fix. There was first a public holiday, and then it took me hours to setup Windows VM, 8+ hours to download source code, 3+ hours to test build... and finally here it is.

**Comment by kenny-y** [comment]
@halton @pozdnyakov @rakuco

**Comment by halton** [comment]
I would suppose this PR is just for Windows build issue for previous PR #3666. So I would give my lgtm.

**Comment by kenny-y** [comment]
Yes positive. No change to previous one except the fix to Windows build.

**Comment by pozdnyakov** [comment]
lgtm

**Comment by halton** [comment]
@pozdnyakov do you mind to do the merge?

**Pull request merged**
