### PR TITLE
Add manifest "start_url" field support for web URL.

### PR DESCRIPTION
**Pull request by seanlong**
Before this change "start_url" filed only support local relative URL,
after this it will also support http/https web URLs

BUG=XWALK-3656

### CODE REVIEW

**Comment by seanlong** [comment]
@pozdnyakov @kenchris PTAL, thanks.

**Comment by pozdnyakov** [comment]
From the http://w3c.github.io/manifest/#start_url-member:

"If url is not same origin as document URL:
    Issue a developer warning that the start_url needs to be same-origin as Document of the top-level browsing context.
    Return a new URL whose input is document URL."
So looks like http/https web URLs cannot be there

**Comment by seanlong** [comment]
Yes, I raised the same question to @kenchris in mail, he replied it would be OK.
@kenchris would you confirm this? Thanks.

**Comment by takethathe** [comment]
@pozdnyakov @kenchris @seanlong 
How about to use http://w3c.github.io/manifest/#scope-member

**Comment by kenchris** [comment]
the spec is written with hosted apps in mind. We do packaged apps (and so will Microsoft for Win10). I think that we need to find out how we can support this @anssik. We need to think about how to avoid man-in-the-middle attacks ect, restriction to https etc.

I can talk to @pozdnyakov @poussa @anssik next week.

**Comment by rakuco** [comment]
I think you mean @anssiko ;-)

**Comment by seanlong** [comment]
@kenchris Do you have decision on this now?
@takethathe I think the "scope" is to specify the manifest working scope which is different from start URL.

**Comment by kenchris** [comment]
Let's follow MS's lead here

**Pull request merged**
