### PR TITLE
[Android] Add LZMA compressed runtime support in download mode

### PR DESCRIPTION
**Pull request by XiaosongWei**
We support both the original XWalkRuntimeLib.apk and the LZMA compressed XWalkRuntimeLibLzma.apk in download mode.

BUG=XWALK-5214

### CODE REVIEW

**Comment by halton** [comment]
@XiaosongWei  please apply one PR one commit rule. Add @heke123 for the lzma commit review.

**Comment by XiaosongWei** [comment]
@halton Understood. I added multiple commits here just because no feedback received on PR#3387 after two weeks. I want to get all download mode related features done in crosswalk-17, please help to speed up review. Thanks!

**Comment by XiaosongWei** [comment]
@lincsoon @axinging @fujunwei @wuhengzhi @xzhan96

**Comment by heke123** [comment]
@XiaosongWei  @halton   
 Sorry for late, no problem for the lzma commit part, LGTM

**Comment by halton** [comment]
@XiaosongWei Understood, but please limit this PR with lzma part only.

**Comment by halton** [comment]
@XiaosongWei please remove the rest of two commits.

**Comment by XiaosongWei** [comment]
@halton updated, thanks!

**Comment by XiaosongWei** [comment]
@halton @lincsoon Can you please help to merge? want to get it done by EOW. Thanks!

**Comment by halton** [comment]
Will merge based on heke's lgtm

**Pull request merged**
