### PR TITLE
[Android] Fix Binary Message Interface instrumentation tests

### PR DESCRIPTION
**Pull request by huningxin**
BUG=XWALK-5093

### CODE REVIEW

**Comment by huningxin** [comment]
fixup of the tests failure for https://github.com/crosswalk-project/crosswalk/pull/3259

**Comment by rakuco** [comment]
lgtm, I'll just wait a little bit for the bots

**Comment by huningxin** [comment]
@rakuco , please take a look. Thanks!

**Comment by huningxin** [comment]
FYI. The xwalk core and xwalk core internal instrumentation tests pass on my side.

**Comment by halton** [comment]
Lgtm merging

**Pull request merged**
