### PR TITLE
Cleanup some mess checked in.

### PR DESCRIPTION
**Pull request by darktears**
This should probably not be here.

### CODE REVIEW

**Comment by darktears** [comment]
@rakuco

**Comment by darktears** [comment]
So apparently it's needed. What a weird name and place to be.

**Comment by rakuco** [comment]
agreed. I think it was added with the LZMA SDK stuff, and it can certainly be put somewhere more reasonable.

**Comment by rakuco** [comment]
> it can certainly be put somewhere more reasonable.

Done in #3198.

**Pull request closed without merging**
