### PR TITLE
[Tizen] Fixed the parsing of widget manifest

### PR DESCRIPTION
**Pull request by rynkowsg**
Problem:    Whitespaces in some nodes and attributes values should be removed.
Solution:   Collapse and trim whitespaces at selected strings.

Links to specification:
    http://www.w3.org/TR/widgets/#rule-for-getting-text-content-with-normalized-white-space-0
    http://www.w3.org/TR/widgets/#rule-for-getting-a-single-attribute-value-0

BUG=XWALK-2775

### CODE REVIEW

**Comment by takethathe** [comment]
@rynkowsg 
Does this patch support the patten like this:
```
<name> Sample <span>Name</span> Test</name>
```

**Comment by rakuco** [comment]
Which reminds me that we should probably have some tests for this change.

**Comment by rynkowsg** [comment]
@takethathe
Yes, the result is as it should be.

**Comment by takethathe** [comment]
LGTM

**Comment by rynkowsg** [comment]
Tests for this change should be [here](https://github.com/crosswalk-project/crosswalk-test-suite/tree/master/webapi/tct-wgtapi01-w3c-tests/widgetinterface/w3c]). I picked some tests but they are broken, in my opinion.

**Comment by rynkowsg** [comment]
@pozdnyakov 
Have you any doubt about that fix? If not, I will be glad of approving it.

**Comment by pozdnyakov** [comment]
lgtm

**Pull request merged**
