### PR TITLE
[Android] Fix the crash issue when use the cordova plugin.

### PR DESCRIPTION
**Pull request by wuhengzhi**
In cordova-plugin-crosswalk-webview, the AttributeSet is null, please
look at [XWalkCordovaView.java#L55](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/blob/master/platforms/android/src/org/crosswalk/engine/XWalkCordovaView.java#L55), app will crash with null pointer.
Add the conditional for AttributeSet.

BUG=XWALK-6960

### CODE REVIEW

**Comment by wuhengzhi** [comment]
@xzhan96 @fujunwei @lincsoon PTAL, thanks.

**Comment by lincsoon** [comment]
LGTM. I was just going to fix this issue. Please also backport to Crosswalk-20 after this patch gets merged.

**Comment by lincsoon** [comment]
@fujunwei It's a little weird in the code of the plugin:
```
    public XWalkCordovaView(Context context, CordovaPreferences preferences) {
        super(setGlobalPrefs(context, preferences), (AttributeSet)null);
    }
```
Why pass a null argument instead of using `XWalkView(Context)` directly?

**Comment by xzhan96** [comment]
> Why pass a null argument instead of using XWalkView(Context) directly?
+1, I am also confused it...

**Pull request merged**
