### PR TITLE
[Android] Export XWalkCookieManager

### PR DESCRIPTION
**Pull request by fujunwei**
Crosswalk cordova plugin need this class to provide ability of accessing cookie in shared mode. Change the name of XWalkCookieManager to XWalkCookieManagerInternal for generating wrapper and bridge of the class.

### CODE REVIEW

**Comment by fujunwei** [comment]
@lincsoon @axinging @halton PTAL, thanks.

**Comment by axinging** [comment]
Several customers use XWalkCookieManager directly. It seems this API not changed, so they can keep using XWalkCookieManager?

About the CookieManagerTest.java, I think use XWalkCookieManager will be better.

**Comment by fujunwei** [comment]
The XWalkCookieManager will be generated by the script of python that will be packaged in jar that will be used by customer.
Use  XWalkCookieManagerInternal instead of XWalkCookieManager  in internal core library.

**Comment by lincsoon** [comment]
LGTM

**Comment by halton** [comment]
LGTM, merging.

**Pull request merged**
