### PR TITLE
Show specail options with the accept attribute

### PR DESCRIPTION
**Pull request by fujunwei**
The following code is allow the user to upload an image from stored files or by taking a photo using camera, but the Camcorder and Voice Recorder options should not be included.
```
<input id="file" type="file" name="file" accept="image/*">
```

BUG=XWALK-3750

### CODE REVIEW

**Comment by fujunwei** [comment]
@lincsoon @wuhengzhi PTAL, thanks.

**Comment by lincsoon** [comment]
Could you give more details in the commit comment?

**Comment by fujunwei** [comment]
Thanks, Done.

**Comment by barryvdh** [comment]
Is this being backported to 17/18?

**Comment by baleboy** [comment]
It should be cherry picked to Crosswalk18 at least

**Pull request merged**
