### PR TITLE
[Android]Fix the issue that 'File chooser' does not assume device lan…

### PR DESCRIPTION
**Pull request by xzhan96**
…guage settings

As the default ChooserActivity will get default title from
internal resource, which includes all languages' string, there
is no need to set the chooser intent title.

BUG=XWALK-5178

### CODE REVIEW

**Comment by xzhan96** [comment]
@lincsoon @axinging @halton @wuhengzhi

**Comment by wuhengzhi** [comment]
LGTM, thanks.

**Comment by rakuco** [comment]
does this need to be backported?

**Comment by xzhan96** [comment]
@rakuco do you mean revert this patch? no need, even customer has another issue, this patch fix the "File chooser" title language issue indeed.

**Comment by xzhan96** [comment]
@rakuco I think so. As there still another language issue of "File chooser", I will backport the patches after fixing another one.

**Pull request merged**
