### PR TITLE
DEPS.xwalk: Roll v8-crosswalk (ba5299d -> 1bdcd37)

### PR DESCRIPTION
**Pull request by huningxin**
1bdcd37 Merge pull request #81 from huningxin/simd-m41-fix-mandelbrot
b394589 [SIMD.js] Fix performance regression of mandelbrot benchmark

### CODE REVIEW

**Comment by huningxin** [comment]
It fixes https://crosswalk-project.org/jira/browse/XWALK-3525 for Crosswalk-13.

**Comment by huningxin** [comment]
@rakuco , please take a look. Thanks!

**Comment by darktears** [comment]
LGTM.

**Comment by darktears** [comment]
Please rebase.

**Comment by huningxin** [comment]
https://github.com/crosswalk-project/crosswalk/commit/956cbca0a3cc52cd5c94d45d75488a8bdef5a3e0 covers this one. So close it. Thanks!

**Pull request closed without merging**
