### PR TITLE
[Android] Implement XWalkContentLifecycleNotifier.

### PR DESCRIPTION
**Pull request by wuhengzhi**
This patch provides a way to observe XWalkView lifecycle on the java
side. By implementing XWalkContentLifecycleNotifier.Observer and
registering with the notifier, clients will get notified when there
are alive instances of XWalkViews (i.e. xwalk_content) or when all
XWalkView instances have been destroyed.

This is useful for APIs which can be disabled when there are no
living XWalkViews, e.g. Network Information API.

This code was ported from upstream,
CL: https://codereview.chromium.org/1419083010

This is Part 1, the observer should also be implemented for XWalkView
lifecycle observers.

BUG=XWALK-5892, XWALK-6178

(cherry picked from commit 210b155f3d9b7a9fca2933982d0217690be284d4)

### CODE REVIEW

**Comment by wuhengzhi** [comment]
@rakuco Please help to review and merge, thanks.

**Comment by rakuco** [comment]
@canadezo: this has backported the original change to Crosswalk 18, and the next beta version will include it.

**Comment by canadezo** [comment]
How can I implement a canary build? I'm currently using 15.44.384.13 

I'm currently using 
`
    repositories {
        maven {
            url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
        }
    }
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    // Testing dependencies
    compile 'org.xwalk:xwalk_core_library:15.44.384.13'
}`
I want to use a Canary build, I don't care which one as long as it doesn't have the networkchangenotifier. Any help? Please & Thank You!

**Comment by rakuco** [comment]
Try taking a look at https://crosswalk-project.org/blog/using-custom-crosswalk-in-cordova-plugin.html and https://crosswalk-project.org/documentation/embedding_crosswalk/crosswalk_aar.html

**Pull request merged**
