### PR TITLE
[Android] Implement save/autofill password part1

### PR DESCRIPTION
**Pull request by XiaosongWei**
This is the part one of the implementation. The overall idea of the
implementation is that we leverage components/password_manager for
password saving/autofill and leverage components/infobars for save
password infobar UI.

This patch is to implement password manager client for password
saving/autofill without UI logic.

Related to XWALK-6038

### CODE REVIEW

**Comment by XiaosongWei** [comment]
@halton @lincsoon @axinging @fujunwei @xzhan96 @wuhengzhi Please take a look, Thanks!

**Comment by darktears** [comment]
LGTM.

**Comment by darktears** [comment]
What is the use case?
There is a major problem is that there is no UI for a person to edit/remove saved logins?
Who asked for it?

The patch itself is LGTM but I wonder the need of the feature.

**Comment by darktears** [comment]
@baleboy FYI

**Comment by rakuco** [comment]
I ended up raising the same questions in XWALK-6038; let's please continue this discussion there.

**Comment by baleboy** [comment]
This was requested by one crosswalk user, although I don't know the details of the app

**Comment by halton** [comment]
@darktears it is requested by Yunshipei (http://www.yunshipei), the new identified customer, who is using HTML5/Web technology for enterprise users. Their app is very likely a browser, this feature is like password manager. The auto save/fill is first step, the management UI feature is TBD.

**Comment by darktears** [comment]
Not LGTM until there is a decent plan.

**Comment by XiaosongWei** [comment]
Yunshipei will keep the patch on their own branch and continue to implement more password management related feature. Crosswalk will not add password management support until there's a decent plan

**Pull request closed without merging**
