### PR TITLE
[Android] Implement XWalkView.setUserAgentString

### PR DESCRIPTION
**Pull request by axinging**
Implement API XWalkView.setUserAgentString for client to set it's own user agent.

BUG=XWALK-3306

### CODE REVIEW

**Comment by axinging** [comment]
@lincsoon @halton @wang16

**Comment by rakuco** [comment]
Does it need a `@since`?

**Comment by axinging** [comment]
@rakuco @kenchris @wang16

**Comment by wang16** [comment]
A test case is preferred.

**Comment by axinging** [comment]
@wang16 Add test case

**Comment by wang16** [comment]
LGTM, thanks.

**Pull request merged**
