### PR TITLE
Revert "[Android] Enable pull-to-refresh"

### PR DESCRIPTION
**Pull request by axinging**
Reverts crosswalk-project/crosswalk#3621.
This will fail tests515, because this introduces android support library's dependence.
While tests515 doesn't include this dependence.
Currently the only direct reference to android support library is core_shell, xwalk
has no other direct reference to android support library. So we are not intending to
introduce this dependence and will revert this commit. We will re-implement this and
remove dependence like android support library in XWALK-6277.
BUG=XWALK-6781

### CODE REVIEW

**Comment by axinging** [comment]
@lincsoon @fujunwei @xzhan96 @wuhengzhi  @rakuco

**Comment by xzhan96** [comment]
lgtm

**Comment by rakuco** [comment]
Please be more verbose in your commit message, which is what matters the most in the end: it does not mention the hash of the commit being reverted (which should've been added automatically by `git revert`), nor does it mention XWALK-6781 and the original pull-to-refresh ticket or explain why this is being done.

**Comment by axinging** [comment]
Hi, @rakuco, just update the comments. BTW, I revert this by click the revert button.

**Comment by rakuco** [comment]
Again, only the pull request message has been updated, not the actual commit message.

**Comment by axinging** [comment]
@rakuco

**Comment by rakuco** [comment]
lgtm, thanks

**Pull request merged**
