### PR TITLE
[Linux]Fix the race condition in XWalkExtensionService

### PR DESCRIPTION
**Pull request by XiaosongWei**
XWalkExtensionServer got deleted in XWalkExtensionData by
XWalkExtensionService while the XWalkExtensionServer pointers are still
accessed by ExtensionServerMessageFilter in IPC thread.

Use WeakPtr to avoid such race condition.

BUG=XWALK-6856

### CODE REVIEW

**Comment by XiaosongWei** [comment]
@rakuco I am unable to reproduce the issue in my local environment and I just added log to check the suspected point, need your help to double confirm whether it works or not.

@darktears @baleboy Please take a look!

**Comment by rakuco** [comment]
I didn't have time to test this today, but looking at the patch I don't see how it would fix that bug: you're just adding weak pointers to the code without checking for their validity in `OnGetExtensions` (and possibly other places).

**Comment by XiaosongWei** [comment]
@rakuco the weak pointers validity check is done in ```OnMessageReceived``` before calling ```OnGetExtension``` and ```OnCreateInstance```

**Comment by rakuco** [comment]
Unfortunately it looks like you did not try a debug build, which would have also helped you try to reproduce the issue in the first place.

```
[89561:89575:0510/190546:FATAL:weak_ptr.cc(26)] Check failed: sequence_checker_.CalledOnValidSequencedThread(). WeakPtrs must be checked on the same sequenced thread.
```

This assert prevents the tests from even running in debug mode.

**Comment by rakuco** [comment]
see also: #3694

**Pull request closed without merging**
