### PR TITLE
[Windows] Autostart application if no paramaters are passed to xwalk.

### PR DESCRIPTION
**Pull request by darktears**
Automatically try to find the manifest.json relative to the xwalk.exe path
in approot/ (which is the place for application files created using
crosswalk-app-tools). If it's not found then crosswalk doesn't start.

### CODE REVIEW

**Comment by darktears** [comment]
@pozdnyakov PTAL it goes with https://github.com/crosswalk-project/crosswalk-app-tools/pull/144

**Comment by darktears** [comment]
@pozdnyakov landed the app-tool part.

**Comment by darktears** [comment]
@pozdnyakov ping

**Comment by rakuco** [comment]
I think Misha is on holidays. rs=me

**Pull request merged**
