### PR TITLE
[lite] disable geolocation and geofencing.

### PR DESCRIPTION
**Pull request by heke123**
Reduce 26K with LZMA on,  add flag DISABLE_GEO_FEATURES

### CODE REVIEW

**Comment by heke123** [comment]
@PeterWangIntel  @halton  Please help to review. thanks.

**Comment by PeterWangIntel** [comment]
LGTM

**Comment by halton** [comment]
The bump DEPS.xwalk PR suppose to submit after chomium/blink PR get merged, otherwise you won't have correct changeset.

**Comment by heke123** [comment]
@halton  rebase done.

**Comment by heke123** [comment]
@halton, pls help to merge. thanks.

**Pull request merged**
