### PR TITLE
DEPS.xwalk: Roll v8-crosswalk(54dc21->efee9f)

### PR DESCRIPTION
**Pull request by chuan9**
Enable SIMD in crosswalk

### CODE REVIEW

**Comment by huningxin** [comment]
@chuan9 , please split it into two PRs and refer to https://github.com/crosswalk-project/crosswalk/commit/bfdc77525257db4e6ce04b14bbed396e16bbd9d5 and https://github.com/crosswalk-project/crosswalk/commit/36593f7d06aed2edf682fc3c15c7e8abbcbb4c10 for commit log message.

**Comment by chuan9** [comment]
ok, I will.

**Comment by rakuco** [comment]
Improving the commit/PR message is important, but I think all changes can remain in the same commit (splitting them does not hurt, but is not required).

**Comment by rakuco** [comment]
Hmm, now you didn't fix the commit message and removed part of the changes, so I'm confused...

**Comment by rakuco** [comment]
Almost there -- see how https://github.com/crosswalk-project/crosswalk/commit/bfdc77525257db4e6ce04b14bbed396e16bbd9d5 lists the commits that are being pulled (you can use `git log --oneline` for that).

**Comment by chuan9** [comment]
@rakuco er... Sorry for confusing you. I have revised the PR.

**Comment by rakuco** [comment]
@chuan9: please adjust the commit message for the commit rolling `DEPS.xwalk` to the format Ningxin mentioned so we can merge the P.

**Comment by rakuco** [comment]
The commits don't seem to have changed. Specifically, commit https://github.com/chuan9/crosswalk/commit/ddd8d65210075a2e4098b410eecb71dfcc6657a9 *must* include the list of commits being pulled in (so `cd src/v8; git log --oneline --no-decorate 54dc21..efee9f`), just like Ningxin showed in previous commits we've merged.

**Comment by chuan9** [comment]
@rakuco Got it, thanks for review.

**Comment by rakuco** [comment]
Thanks!

**Pull request merged**
